config/routes.rb
Rails.application.routes.draw do
  resources :goods
  resources :razdels
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :razdel
end

app/models/razdel.rb
class Razdel < ApplicationRecord
    has_many :goods
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :set_good, only: [:show, :edit, :update, :destroy]

  # GET /goods
  # GET /goods.json
  def index
    @goods = Good.all
  end

  # GET /goods/1
  # GET /goods/1.json
  def show
  end

  # GET /goods/new
  def new
    @good = Good.new
  end

  # GET /goods/1/edit
  def edit
  end

  # POST /goods
  # POST /goods.json
  def create
    @good = Good.new(good_params)

    respond_to do |format|
      if @good.save
        format.html { redirect_to @good, notice: 'Good was successfully created.' }
        format.json { render :show, status: :created, location: @good }
      else
        format.html { render :new }
        format.json { render json: @good.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goods/1
  # PATCH/PUT /goods/1.json
  def update
    respond_to do |format|
      if @good.update(good_params)
        format.html { redirect_to @good, notice: 'Good was successfully updated.' }
        format.json { render :show, status: :ok, location: @good }
      else
        format.html { render :edit }
        format.json { render json: @good.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goods/1
  # DELETE /goods/1.json
  def destroy
    @good.destroy
    respond_to do |format|
      format.html { redirect_to goods_url, notice: 'Good was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_good
      @good = Good.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def good_params
      params.require(:good).permit(:name, :article, :content, :razdel_id, :rubles, :availability)
    end
end

app/controllers/razdels_controller.rb
class RazdelsController < ApplicationController
  before_action :set_razdel, only: [:show, :edit, :update, :destroy]

  # GET /razdels
  # GET /razdels.json
  def index
    @razdels = Razdel.all
  end

  # GET /razdels/1
  # GET /razdels/1.json
  def show
  end

  # GET /razdels/new
  def new
    @razdel = Razdel.new
  end

  # GET /razdels/1/edit
  def edit
  end

  # POST /razdels
  # POST /razdels.json
  def create
    @razdel = Razdel.new(razdel_params)

    respond_to do |format|
      if @razdel.save
        format.html { redirect_to @razdel, notice: 'Razdel was successfully created.' }
        format.json { render :show, status: :created, location: @razdel }
      else
        format.html { render :new }
        format.json { render json: @razdel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /razdels/1
  # PATCH/PUT /razdels/1.json
  def update
    respond_to do |format|
      if @razdel.update(razdel_params)
        format.html { redirect_to @razdel, notice: 'Razdel was successfully updated.' }
        format.json { render :show, status: :ok, location: @razdel }
      else
        format.html { render :edit }
        format.json { render json: @razdel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /razdels/1
  # DELETE /razdels/1.json
  def destroy
    @razdel.destroy
    respond_to do |format|
      format.html { redirect_to razdels_url, notice: 'Razdel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_razdel
      @razdel = Razdel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def razdel_params
      params.require(:razdel).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/razdels_helper.rb
module RazdelsHelper
end

app/views/goods/_form.html.erb
<%= form_with(model: good, local: true) do |form| %>
  <% if good.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(good.errors.count, "error") %> prohibited this good from being saved:</h2>

      <ul>
      <% good.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :article %>
    <%= form.text_field :article %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :razdel_id %>
    <%= form.text_field :razdel_id %>
  </div>

  <div class="field">
    <%= form.label :rubles %>
    <%= form.text_field :rubles %>
  </div>

  <div class="field">
    <%= form.label :availability %>
    <%= form.check_box :availability %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/goods/edit.html.erb
<h1>Editing Good</h1>

<%= render 'form', good: @good %>

<%= link_to 'Show', @good %> |
<%= link_to 'Back', goods_path %>

app/views/goods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Goods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Article</th>
      <th>Content</th>
      <th>Razdel</th>
      <th>Rubles</th>
      <th>Availability</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goods.each do |good| %>
      <tr>
        <td><%= good.name %></td>
        <td><%= good.article %></td>
        <td><%= good.content %></td>
        <td><%= good.razdel %></td>
        <td><%= good.rubles %></td>
        <td><%= good.availability %></td>
        <td><%= link_to 'Show', good %></td>
        <td><%= link_to 'Edit', edit_good_path(good) %></td>
        <td><%= link_to 'Destroy', good, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Good', new_good_path %>

app/views/goods/new.html.erb
<h1>New Good</h1>

<%= render 'form', good: @good %>

<%= link_to 'Back', goods_path %>

app/views/goods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @good.name %>
</p>

<p>
  <strong>Article:</strong>
  <%= @good.article %>
</p>

<p>
  <strong>Content:</strong>
  <%= @good.content %>
</p>

<p>
  <strong>Razdel:</strong>
  <%= @good.razdel %>
</p>

<p>
  <strong>Rubles:</strong>
  <%= @good.rubles %>
</p>

<p>
  <strong>Availability:</strong>
  <%= @good.availability %>
</p>

<%= link_to 'Edit', edit_good_path(@good) %> |
<%= link_to 'Back', goods_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shopadmin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/razdels/_form.html.erb
<%= form_with(model: razdel, local: true) do |form| %>
  <% if razdel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(razdel.errors.count, "error") %> prohibited this razdel from being saved:</h2>

      <ul>
      <% razdel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/razdels/edit.html.erb
<h1>Editing Razdel</h1>

<%= render 'form', razdel: @razdel %>

<%= link_to 'Show', @razdel %> |
<%= link_to 'Back', razdels_path %>

app/views/razdels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Razdels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @razdels.each do |razdel| %>
      <tr>
        <td><%= razdel.name %></td>
        <td><%= link_to 'Show', razdel %></td>
        <td><%= link_to 'Edit', edit_razdel_path(razdel) %></td>
        <td><%= link_to 'Destroy', razdel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Razdel', new_razdel_path %>

app/views/razdels/new.html.erb
<h1>New Razdel</h1>

<%= render 'form', razdel: @razdel %>

<%= link_to 'Back', razdels_path %>

app/views/razdels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @razdel.name %>
</p>

<%= link_to 'Edit', edit_razdel_path(@razdel) %> |
<%= link_to 'Back', razdels_path %>